FROM ubuntu:24.4

SHELL ["/bin/bash", "-lc"]

WORKDIR /app

COPY /app/main.bf .


RUN apt update; apt-get -y install make


RUN git clone https://github.com/catseye/Befunge-93.git && \
    cd Befunge-93 && \
    make && \
    mv bin/bef ../


RUN rm -rf Befunge-93


CMD ["./bef", "main.bf"]