FROM ubuntu:24.4

SHELL ["/bin/bash", "-lc"]

WORKDIR /app

COPY /app/main.bf .

ONBUILD RUN apt update; apt-get -y install make

ONBUILD RUN git clone https://github.com/catseye/Befunge-93.git && \
    cd Befunge-93 && \
    make && \
    mv bin/bef ../


ONBUILD RUN rm -rf Befunge-93

ONBUILD CMD ["./bef", "main.bf"]