FROM python:3.12-bookworm

SHELL ["/bin/bash", "-lc"]

WORKDIR /app

COPY app .

ONBUILD RUN if [ -f requirements.txt ]; then \
    pip install -r requirements.txt \
    else \
        echo "requirements.txt not found."; \
        exit 1; \
    fi

ONBUILD CMD ["python", "-m", "app"]