FROM python:3.12-bookworm

SHELL ["/bin/bash", "-lc"]

ONBUILD WORKDIR /app

ONBUILD COPY requirements.txt .

ONBUILD RUN pip install -r requirements.txt

ONBUILD COPY app/ .

ONBUILD CMD ["python", "-m", "app"]