FROM node:20.9 AS whanos-javascript

COPY . .

RUN if [-f package.json]; then \
        npm install; \
    else \
        echo "package.json not found."; \
        exit 1; \
    fi

CMD ["node", "."]
