name: Docusaurus Preview

on:
  pull_request:
    branches:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs

    permissions:
      contents: write
      pull-requests: write  # to comment back the preview URL

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build docs
        run: |
          export BASE_URL="/Whanos/previews/${{ github.head_ref }}/"
          npm run build

      - name: Deploy preview to GitHub Pages (branch folder)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/build
          destination_dir: previews/${{ github.head_ref }}
          commit_message: "🧪 Deploy preview for ${{ github.head_ref }} at ${{ github.sha }}"

      - name: Comment preview link on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: docs-preview
          message: |
            🚀 **Docs Preview Available!**
            👉 https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/previews/${{ github.head_ref }}/
